version: 2

updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    # These updates are mainly informational.
    # Updating go.mod does (almost) nothing; it's the bazel dependencies
    # which matter.
    interval: monthly
  open-pull-requests-limit: 10
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: weekly
